### ISSUE TITLE
How to cite data sets?

### ISSUE THREAD

**Issue by knit-bee** [NEISSproject/NERDatasets#1]
Hi,
I'd like to use your data sets for an analysis and I was wondering how I should cite them? As I understood it, the citation provided in the readme only refers to the source texts not to tagged data.
Is there a DOI I could use?
Thank you in advance!
Kind regards,
Luise

**Comment by KonradSperfeld** [comment]
Hi Luise,
thank you for your interest in the NER datasets. You can cite them by citing the paper where we introduced them:
Zöllner, J.; Sperfeld, K.; Wick, C.; Labahn, R. Optimizing Small BERTs Trained for German NER. Information 2021, 12, 443. [https://doi.org/10.3390/info12110443](https://doi.org/10.3390/info12110443) 
I'm sorry, we forgot to add this information here in the repository. I will add it to the README of the repository.
Greetings,
Konrad

**Comment by knit-bee** [comment]
Hi Konrad,
thanks a lot for your answer and the information!
Kind regards, 
Luise
